language: haskell

before_install:
  - ghc --version
  - cabal --version

ghc:
  - 7.8
  - 7.6
  - 7.4

script:
  - cabal configure --enable-tests --enable-coverage && cabal build && cabal test

after_script:
  - cabal install hpc-coveralls