env:
  - CABALVER=1.22 GHCVER=7.10.3

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:$PATH

install:
  - cabal-$CABALVER update
  - travis_retry sudo apt-get -q -y install hlint || cabal-$CABALVER install hlint
  - cabal-$CABALVER install --only-dependencies --enable-tests . hpc-coveralls
  - cabal-$CABALVER install hpc-coveralls

script:
  - cabal-$CABALVER configure --enable-tests --enable-coverage -v2
  - cabal-$CABALVER build
  - cabal-$CABALVER test --show-details=always
  - run-cabal-test --show-details=always
  - hpc-coveralls --exclude-dir=test test || true

after_script:
  - hpc-coveralls --coverage-mode=StrictlyFullLines tests